# ==============================
# split_by_modality.py 설정 파일
# ==============================

rid_col: "RID" # 학습용 parquet의 unique id
label_col: "clicked" # train에는 존재, test에서는 "" 로 둠

rows_per_chunk: 400000 # 청크 단위 처리 (메모리 상황에 맞게 조정)
hash_num_buckets: 1048576
hash_seed: 17

out_names:
  cont: "cont"
  cat_hash: "cat_hash"
  cat_vocab: "cat_vocab"
  seq: "seq"
  seq_hash: "seq_hash"
  meta: "meta"

# ------------------------------
# 연속형 변수 (예시)
# ------------------------------
continuous:
  - { name: "feat_a_5", method: "standard" }
  - { name: "feat_a_14", method: "log1p+standard" }

  - { name: "feat_b_1", method: "log1p+standard" }
  - { name: "feat_b_2", method: "robust" }
  - { name: "feat_b_3", method: "log1p+standard" }
  - { name: "feat_b_4", method: "standard" }
  - { name: "feat_b_5", method: "robust" }
  - { name: "feat_b_6", method: "log1p+standard" }

  - { name: "feat_c_1", method: "standard" }
  - { name: "feat_c_2", method: "standard" }

  - { name: "feat_c_3", method: "standard" }
  - { name: "feat_c_4", method: "standard" }
  - { name: "feat_c_5", method: "standard" }
  - { name: "feat_c_6", method: "standard" }
  - { name: "feat_c_7", method: "standard" }
  - { name: "feat_c_8", method: "standard" }

  - { name: "feat_d_4", method: "log1p+standard" }

  - { name: "feat_e_1", method: "log1p+standard" }
  - { name: "feat_e_2", method: "standard" }
  - { name: "feat_e_3", method: "log1p+standard" }
  - { name: "feat_e_5", method: "standard" }
  - { name: "feat_e_6", method: "standard" }
  - { name: "feat_e_7", method: "log1p+standard" }
  - { name: "feat_e_8", method: "standard" }
  - { name: "feat_e_9", method: "robust" }
  - { name: "feat_e_10", method: "standard" }

  - { name: "history_a_1", method: "standard" }
  - { name: "history_a_2", method: "standard" }
  - { name: "history_a_3", method: "standard" }
  - { name: "history_a_4", method: "robust" }
  - { name: "history_a_5", method: "standard" }
  - { name: "history_a_6", method: "robust" }
  - { name: "history_a_7", method: "robust" }

  - { name: "history_b_1", method: "log1p+robust" }
  - { name: "history_b_2", method: "log1p+robust" }
  - { name: "history_b_3", method: "log1p+robust" }
  - { name: "history_b_4", method: "log1p+robust" }
  - { name: "history_b_5", method: "log1p+robust" }
  - { name: "history_b_6", method: "standard" }
  - { name: "history_b_7", method: "log1p+robust" }
  - { name: "history_b_8", method: "log1p+robust" }
  - { name: "history_b_9", method: "standard" }
  - { name: "history_b_10", method: "log1p+robust" }
  - { name: "history_b_11", method: "log1p+robust" }
  - { name: "history_b_12", method: "standard" }
  - { name: "history_b_13", method: "log1p+robust" }
  - { name: "history_b_14", method: "log1p+robust" }
  - { name: "history_b_15", method: "standard" }
  - { name: "history_b_16", method: "log1p+robust" }
  - { name: "history_b_17", method: "standard" }
  - { name: "history_b_18", method: "log1p+robust" }
  - { name: "history_b_19", method: "standard" }
  - { name: "history_b_20", method: "standard" }
  - { name: "history_b_21", method: "standard" }
  - { name: "history_b_22", method: "log1p+robust" }
  - { name: "history_b_23", method: "log1p+robust" }
  - { name: "history_b_24", method: "log1p+robust" }
  - { name: "history_b_25", method: "standard" }
  - { name: "history_b_26", method: "log1p+robust" }
  - { name: "history_b_27", method: "log1p+robust" }
  - { name: "history_b_28", method: "log1p+robust" }
  - { name: "history_b_29", method: "log1p+robust" }
  - { name: "history_b_30", method: "log1p+robust" }

# ------------------------------
# 해시 인코딩이 필요한 범주형
#   (고유값이 수천~수백만 이상인 컬럼들)
# ------------------------------
categorical_hash: []

# ------------------------------
# vocab / identity 인코딩 범주형
# ------------------------------
categorical_vocab:
  - "gender"
  - "age_group"
  - "day_of_week"
  - "inventory_id"
  - "hour"

  - "feat_a_1"
  - "feat_a_2"
  - "feat_a_3"
  - "feat_a_4"
  - "feat_a_6"
  - "feat_a_7"
  - "feat_a_8"
  - "feat_a_9"
  - "feat_a_10"
  - "feat_a_11"
  - "feat_a_12"
  - "feat_a_13"
  - "feat_a_15"
  - "feat_a_16"
  - "feat_a_17"
  - "feat_a_18"

  - "feat_d_1"
  - "feat_d_2"
  - "feat_d_3"
  - "feat_d_5"
  - "feat_d_6"

  - "feat_e_4"

  - "l_feat_1"
  - "l_feat_2"
  - "l_feat_3"
  - "l_feat_4"
  - "l_feat_5"
  - "l_feat_6"
  - "l_feat_7"
  - "l_feat_8"
  - "l_feat_9"
  - "l_feat_10"
  - "l_feat_11"
  - "l_feat_12"
  - "l_feat_14"
  - "l_feat_15"
  - "l_feat_16"
  - "l_feat_17"
  - "l_feat_18"
  - "l_feat_19"
  - "l_feat_20"
  - "l_feat_21"
  - "l_feat_22"
  - "l_feat_23"
  - "l_feat_24"
  - "l_feat_25"
  - "l_feat_26"
  - "l_feat_27"
# ------------------------------
# vocab 인코딩 모드
# ------------------------------
# identity_plus1 : 원래 코드 +1, 결측은 0 → PAD/OOV=0 예약
vocab_encoding:
  default: "identity_plus1"
  per_column: {}

# ------------------------------
# 시퀀스 컬럼
# ------------------------------
sequence:
  columns: ["seq"]
  max_len: 6000 # 99% 절단 기준
  keep: "tail" # 최근 행동 유지
  buckets: 1048576 # hash embedding bucket 크기

